// angular-starter-webapp/src/app/components/ui/card.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'ui-card',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm',
    'data-slot': 'card',
  },
})
export class UiCardComponent {}

@Component({
  selector: 'ui-card-header',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'flex flex-col gap-1.5 px-6',
    'data-slot': 'card-header',
  },
})
export class UiCardHeaderComponent {}

@Component({
  selector: 'ui-card-title',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'block leading-none font-semibold',
    'data-slot': 'card-title',
  },
})
export class UiCardTitleComponent {}

@Component({
  selector: 'ui-card-description',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'block text-muted-foreground text-sm',
    'data-slot': 'card-description',
  },
})
export class UiCardDescriptionComponent {}

@Component({
  selector: 'ui-card-content',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'block px-6',
    'data-slot': 'card-content',
  },
})
export class UiCardContentComponent {}

@Component({
  selector: 'ui-card-footer',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'flex items-center px-6',
    'data-slot': 'card-footer',
  },
})
export class UiCardFooterComponent {}

// react-starter-webapp/src/components/ui/card.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="card"
      className={cn(
        'bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm',
        className
      )}
      {...props}
    />
  )
}

function CardHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="card-header"
      className={cn(
        '@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6',
        className
      )}
      {...props}
    />
  )
}

function CardTitle({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="card-title"
      className={cn('leading-none font-semibold', className)}
      {...props}
    />
  )
}

function CardDescription({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="card-description"
      className={cn('text-muted-foreground text-sm', className)}
      {...props}
    />
  )
}

function CardAction({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="card-action"
      className={cn('col-start-2 row-span-2 row-start-1 self-start justify-self-end', className)}
      {...props}
    />
  )
}

function CardContent({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="card-content"
      className={cn('px-6', className)}
      {...props}
    />
  )
}

function CardFooter({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="card-footer"
      className={cn('flex items-center px-6 [.border-t]:pt-6', className)}
      {...props}
    />
  )
}

export { Card, CardHeader, CardFooter, CardTitle, CardAction, CardDescription, CardContent }
