// react-starter-webapp/src/components/ui/alert.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const alertVariants = cva(
  'relative w-full rounded-lg border px-4 py-3 text-sm grid has-[>svg]:grid-cols-[calc(var(--spacing)*4)_1fr] grid-cols-[0_1fr] has-[>svg]:gap-x-3 gap-y-0.5 items-start [&>svg]:size-4 [&>svg]:translate-y-0.5 [&>svg]:text-current',
  {
    variants: {
      variant: {
        default: 'bg-card text-card-foreground',
        destructive:
          'text-destructive bg-card [&>svg]:text-current *:data-[slot=alert-description]:text-destructive/90',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
)

function Alert({
  className,
  variant,
  ...props
}: React.HTMLAttributes<HTMLDivElement> & VariantProps<typeof alertVariants>) {
  return (
    <div
      data-slot="alert"
      role="alert"
      className={cn(alertVariants({ variant }), className)}
      {...props}
    />
  )
}

function AlertTitle({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="alert-title"
      className={cn('col-start-2 line-clamp-1 min-h-4 font-medium tracking-tight', className)}
      {...props}
    />
  )
}

function AlertDescription({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="alert-description"
      className={cn('text-muted-foreground col-start-2 grid justify-items-start gap-1 text-sm [&_p]:leading-relaxed', className)}
      {...props}
    />
  )
}

export { Alert, AlertTitle, AlertDescription }

// angular-starter-webapp/src/app/components/ui/alert.component.ts
import { Component, Input, HostBinding } from '@angular/core'
import { cva, type VariantProps } from 'class-variance-authority'

const alertVariants = cva(
  'relative w-full rounded-lg border px-4 py-3 text-sm grid grid-cols-[0_1fr] gap-y-0.5 items-start',
  {
    variants: {
      variant: {
        default: 'bg-card text-card-foreground',
        destructive: 'text-destructive bg-card',
      },
    },
    defaultVariants: { variant: 'default' },
  }
)

type AlertVariant = VariantProps<typeof alertVariants>['variant']

@Component({
  selector: 'ui-alert',
  standalone: true,
  template: `<ng-content />`,
  host: { 'data-slot': 'alert', role: 'alert' },
})
export class UiAlertComponent {
  @Input() variant: AlertVariant = 'default'

  @HostBinding('class')
  get hostClass() {
    return alertVariants({ variant: this.variant })
  }
}

@Component({
  selector: 'ui-alert-title',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'block col-start-2 line-clamp-1 font-medium tracking-tight',
    'data-slot': 'alert-title',
  },
})
export class UiAlertTitleComponent {}

@Component({
  selector: 'ui-alert-description',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'block text-muted-foreground col-start-2 text-sm',
    'data-slot': 'alert-description',
  },
})
export class UiAlertDescriptionComponent {}
