// react-starter-webapp/src/components/ui/tabs.tsx
import * as React from 'react'
import * as TabsPrimitive from '@radix-ui/react-tabs'
import { cn } from '@/lib/utils'

function Tabs({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Root>) {
  return (
    <TabsPrimitive.Root
      data-slot="tabs"
      className={cn('flex flex-col gap-2', className)}
      {...props}
    />
  )
}

function TabsList({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.List>) {
  return (
    <TabsPrimitive.List
      data-slot="tabs-list"
      className={cn(
        'bg-muted text-muted-foreground inline-flex h-9 w-fit items-center justify-center rounded-lg p-[3px]',
        className
      )}
      {...props}
    />
  )
}

function TabsTrigger({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Trigger>) {
  return (
    <TabsPrimitive.Trigger
      data-slot="tabs-trigger"
      className={cn(
        "data-[state=active]:bg-background dark:data-[state=active]:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:outline-ring dark:data-[state=active]:border-input dark:data-[state=active]:bg-input/30 text-foreground dark:text-muted-foreground inline-flex h-[calc(100%-1px)] flex-1 items-center justify-center gap-1.5 rounded-md border border-transparent px-2 py-1 text-sm font-medium whitespace-nowrap transition-[color,box-shadow] focus-visible:ring-[3px] focus-visible:outline-1 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:shadow-sm [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        className
      )}
      {...props}
    />
  )
}

function TabsContent({ className, ...props }: React.ComponentProps<typeof TabsPrimitive.Content>) {
  return (
    <TabsPrimitive.Content
      data-slot="tabs-content"
      className={cn('flex-1 outline-none', className)}
      {...props}
    />
  )
}

export { Tabs, TabsList, TabsTrigger, TabsContent }

// angular-starter-webapp/src/app/components/ui/tabs.component.ts
import { Component, Input, Output, EventEmitter, inject, HostBinding } from '@angular/core'
import { cn } from '../../lib/utils'

@Component({
  selector: 'ui-tabs',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'flex flex-col gap-2',
    'data-slot': 'tabs',
  },
})
export class UiTabsComponent {
  @Input() value = ''
  @Output() valueChange = new EventEmitter<string>()
}

@Component({
  selector: 'ui-tabs-list',
  standalone: true,
  template: `<ng-content />`,
  host: {
    class: 'bg-muted text-muted-foreground inline-flex h-9 w-fit items-center justify-center rounded-lg p-[3px]',
    'data-slot': 'tabs-list',
    role: 'tablist',
  },
})
export class UiTabsListComponent {}

@Component({
  selector: 'ui-tabs-trigger',
  standalone: true,
  template: `
    <button
      [class]="cn(
        'inline-flex h-[calc(100%-1px)] flex-1 items-center justify-center gap-1.5 rounded-md border border-transparent px-2 py-1 text-sm font-medium whitespace-nowrap transition-all disabled:pointer-events-none disabled:opacity-50 cursor-pointer',
        active ? 'bg-background text-foreground shadow-sm border-input' : 'text-muted-foreground hover:text-foreground'
      )"
      [attr.data-state]="active ? 'active' : 'inactive'"
      data-slot="tabs-trigger"
      role="tab"
      (click)="handleClick()"
    >
      <ng-content />
    </button>
  `,
})
export class UiTabsTriggerComponent {
  private tabs = inject(UiTabsComponent, { optional: true })

  @Input({ required: true }) value!: string

  get active() {
    return this.tabs?.value === this.value
  }

  handleClick() {
    this.tabs?.valueChange.emit(this.value)
  }

  protected cn = cn
}
